import type { VisitorRow } from "@/components/tables/visitors-table";

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();

export const MOCK_VISITORS: VisitorRow[] = [
  {
    id: "v_001",
    first_seen: hoursAgo(28),
    last_seen: hoursAgo(2),
    ip_hash: "a1b2c3d4",
    country: "BH",
    city: "Manama",
    company_name: "Investcorp",
    company_domain: "investcorp.com",
    industry: "Financial services",
    company_size: "501-1000",
    pages_viewed: 7,
    landing_page: "/private-wealth",
    referrer: "google.com",
    utm_source: "google",
    utm_medium: "cpc",
    utm_campaign: "private-wealth-bh",
    device: "Desktop",
    browser: "Chrome",
  },
  {
    id: "v_002",
    first_seen: hoursAgo(50),
    last_seen: hoursAgo(49),
    ip_hash: "e5f6a7b8",
    country: "AE",
    city: "Dubai",
    company_name: "Emirates NBD",
    company_domain: "emiratesnbd.com",
    industry: "Banking",
    company_size: "5000+",
    pages_viewed: 3,
    landing_page: "/about",
    referrer: "linkedin.com",
    utm_source: "linkedin",
    utm_medium: "social",
    utm_campaign: null,
    device: "Desktop",
    browser: "Safari",
  },
  {
    id: "v_003",
    first_seen: hoursAgo(120),
    last_seen: hoursAgo(118),
    ip_hash: "c9d0e1f2",
    country: "SA",
    city: "Riyadh",
    company_name: "PIF",
    company_domain: "pif.gov.sa",
    industry: "Sovereign wealth",
    company_size: "1001-5000",
    pages_viewed: 12,
    landing_page: "/institutional",
    referrer: null,
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    device: "Desktop",
    browser: "Edge",
  },
  {
    id: "v_004",
    first_seen: hoursAgo(8),
    last_seen: hoursAgo(8),
    ip_hash: "1a2b3c4d",
    country: "KW",
    city: "Kuwait City",
    company_name: null,
    company_domain: null,
    industry: null,
    company_size: null,
    pages_viewed: 1,
    landing_page: "/",
    referrer: "google.com",
    utm_source: "google",
    utm_medium: "organic",
    utm_campaign: null,
    device: "Mobile",
    browser: "Chrome",
  },
  {
    id: "v_005",
    first_seen: hoursAgo(72),
    last_seen: hoursAgo(70),
    ip_hash: "5e6f7a8b",
    country: "GB",
    city: "London",
    company_name: "Schroders",
    company_domain: "schroders.com",
    industry: "Asset management",
    company_size: "5000+",
    pages_viewed: 5,
    landing_page: "/private-equity",
    referrer: "bing.com",
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    device: "Desktop",
    browser: "Firefox",
  },
  {
    id: "v_006",
    first_seen: hoursAgo(4),
    last_seen: hoursAgo(3),
    ip_hash: "9c0d1e2f",
    country: "QA",
    city: "Doha",
    company_name: "Qatar Investment Authority",
    company_domain: "qia.qa",
    industry: "Sovereign wealth",
    company_size: "501-1000",
    pages_viewed: 9,
    landing_page: "/insights/gcc-outlook-2026",
    referrer: "twitter.com",
    utm_source: "twitter",
    utm_medium: "social",
    utm_campaign: "thought-leadership-q2",
    device: "Tablet",
    browser: "Safari",
  },
];
